### ISSUE TITLE
SVG issue

### ISSUE THREAD

**Issue by marksantiago290** [BTC415/Workana-Test-Project#15]
Some svgs are not correct as expected.
Plz check

**Comment by imcrazysteven** [comment]
Please be specific in more detail

**Comment by marksantiago290** [comment]
I mean, calendar svg, and wallet svg etc

**Comment by imcrazysteven** [comment]
Okay. Let me check and let you know soon.

**Comment by imcrazysteven** [comment]
Fixed. plz check, leave comment and merge.

**Comment by marksantiago290** [comment]
Good
